START TRANSACTION;
DELETE FROM History;
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '202550aa-f139-48f7-bcff-87e1c7c0767c',
                'La Gallina de los Huevos de Oro',
                'The Hen of the Golden Eggs',
                'A Galinha dos Ovos de Ouro',
                'Cuento clásico de magia y corazón, una gallina especial que da lecciones de razón. 🥚✨',
                'Description: A classic tale of magic and delight, where a special hen shines with wisdom and light. 🥚✨',
                'Descrição: Um conto clássico de magia e emoção, onde uma galinha ensina com o coração. 🥚✨',
                '202550aa-f139-48f7-bcff-87e1c7c0767c_cover_.png',
                '202550aa-f139-48f7-bcff-87e1c7c0767c.png',
                NULL,
                '202550aa-f139-48f7-bcff-87e1c7c0767c.mp3',
                1, 
                1,
                0,
                '#f07706',
                NULL,
                '#f07706',
                '#7f3105',
                '#f8d87e',
                '#5c402c',
                '#a4a47c',
                '#9c9474',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '215e778c-0ece-41ae-a4dc-5bfce4dc6a2f',
                '🎶💃 Jennifer y el Ritmo de su Corazón',
                '🎶💃 Jennifer and the Rhythm of Her Heart',
                '🎶💃 Jennifer e o Ritmo do Seu Coração',
                'Cuento inspirado en Jennifer, una niña llena de emoción, que bailaba sus sueños al ritmo del corazón. 🎶💃',
                'Story inspired by Jennifer, a girl full of light, who danced her dreams with all her might. 🎶💃',
                'Conto inspirado em Jennifer, uma menina cheia de paixão, que dançava seus sonhos com alma e emoção. 🎶💃',
                '215e778c-0ece-41ae-a4dc-5bfce4dc6a2f_cover_.png',
                '215e778c-0ece-41ae-a4dc-5bfce4dc6a2f.png',
                NULL,
                '215e778c-0ece-41ae-a4dc-5bfce4dc6a2f.mp3',
                2, 
                1,
                0,
                '#f19f0b',
                NULL,
                '#f19f0b',
                '#733012',
                '#fad56e',
                '#68325f',
                '#936e05',
                '#5861a1',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '245cac42-a6af-4167-b855-cb9f84a03998',
                '🚴☀️Egar y el Vuelo de su Bicicleta',
                '🚴☀️Egar and the Flight of His Bicycle',
                ' 🚴☀️Egar e o Voo da Sua Bicicleta',
                'Cuento inspirado en Egar, un niño lleno de pasión, que subía montañas siguiendo su corazón. 🚴‍♂️🌟',
                'Description: Story inspired by Egar, a boy full of dreams, who climbed great heights riding on hope''s beams. 🚴‍♂️🌟',
                'Conto inspirado em Egar, com coragem e paixão, que pedalava nas alturas com o coração. 🚴‍♂️🌟',
                '245cac42-a6af-4167-b855-cb9f84a03998_cover_.png',
                '245cac42-a6af-4167-b855-cb9f84a03998.png',
                NULL,
                '245cac42-a6af-4167-b855-cb9f84a03998.mp3',
                2, 
                1,
                0,
                '#e29b09',
                NULL,
                '#e29b09',
                '#6d1608',
                '#7abfe5',
                '#304020',
                '#e0dac6',
                '#969452',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '27da33bb-ceb7-4e49-804b-12f44991ecbc',
                '🧠🚀 Katherine y los Números del Espacio',
                '🧠🚀 Katherine and the Numbers of Space',
                '🧠🚀 Katherine e os Números do Espaço',
                'Cuento inspirado en Katherine, mente brillante y soñadora, que calculaba trayectorias como una estrella pensadora. 🧠🚀',
                'Story inspired by Katherine, a dreamer bright and wise, who guided astronauts through starry skies. 🧠🚀',
                'Conto inspirado em Katherine, com mente cheia de luz, que ajudava foguetes a encontrar sua cruz. 🧠🚀',
                '27da33bb-ceb7-4e49-804b-12f44991ecbc_cover_.jpg',
                '27da33bb-ceb7-4e49-804b-12f44991ecbc.jpg',
                NULL,
                '27da33bb-ceb7-4e49-804b-12f44991ecbc.MP3',
                2, 
                1,
                0,
                '#a9561b',
                NULL,
                '#a9561b',
                '#72370e',
                '#fbd686',
                '#344c54',
                '#946604',
                '#a87f50',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '2ae095ee-b127-4a9d-917c-3be37bbd7856',
                '🎼🌍 Beethoven y la Música del Alma',
                '🎼🌍Beethoven and the Music of the Soul',
                '🎼🌍Beethoven e a Música da Alma',
                '"Cuento inspirado en Beethoven, una historia sobre la pasión y cómo la música puede cambiar el mundo."',
                '"Story inspired by Beethoven, a tale about passion and how music can change the world."',
                '"História inspirada em Beethoven, uma história sobre paixão e como a música pode mudar o mundo."',
                '2ae095ee-b127-4a9d-917c-3be37bbd7856_cover_.jpeg',
                '2ae095ee-b127-4a9d-917c-3be37bbd7856.jpeg',
                NULL,
                '2ae095ee-b127-4a9d-917c-3be37bbd7856.mp3',
                2, 
                1,
                0,
                '#d6612a',
                NULL,
                '#d6612a',
                '#380c04',
                '#f7e8b0',
                '#7e513d',
                '#ceaf9d',
                '#a06349',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '2c73ed2b-1127-4831-9306-a9e5da5decef',
                'Maicol y la canción que nació del corazón',
                'Maicol and the Song Born from the Heart',
                'Maicol e a Canção Nascida do Coração',
                'Un cuento mágico sobre un niño llamado Michael que descubrió su brillo interior a través de la música y los sueños.',
                'A magical tale about a boy named Michael who found his inner light through music and dreams.',
                'Um conto mágico sobre um menino chamado Michael que descobriu sua luz interior através da música e dos sonhos.',
                '2c73ed2b-1127-4831-9306-a9e5da5decef_cover_.png',
                '2c73ed2b-1127-4831-9306-a9e5da5decef.png',
                NULL,
                '2c73ed2b-1127-4831-9306-a9e5da5decef.MP3',
                2, 
                1,
                0,
                '#fcb209',
                NULL,
                '#fcb209',
                '#881804',
                '#ecc464',
                '#32505e',
                '#d2b599',
                '#8e5e46',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '2fea1068-2359-46a9-bf54-25ef54030f74',
                '🚀🧠 Elon y las Ideas que Tocan el Cielo',
                '🚀🧠 Elon and the Ideas that Reach the Sky',
                '🚀🧠  Elon e as Ideias que Tocam o Céu',
                'Cuento inspirado en la vida de Elon, una historia sobre la innovación y cómo soñar en grande puede llevarte más allá de las estrellas.',
                'A story inspired by the life of Elon, about innovation and how dreaming big can take you beyond the stars.',
                'Conto inspirado na vida de Elon, uma história sobre inovação e como sonhar grande pode te levar além das estrelas.',
                '2fea1068-2359-46a9-bf54-25ef54030f74_cover_.jpeg',
                '2fea1068-2359-46a9-bf54-25ef54030f74.jpeg',
                NULL,
                '2fea1068-2359-46a9-bf54-25ef54030f74.mp3',
                2, 
                1,
                0,
                '#1687d4',
                NULL,
                '#1687d4',
                '#0c2f71',
                '#edc38f',
                '#3d2f51',
                '#c2b5c3',
                '#49578c',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '3ea6fc9d-aa39-4460-b2d2-5f85772bafdd',
                'Ali Babá y los Cuarenta Ladrones',
                'Ali Baba and the Forty Thieves',
                'Ali Babá e os Quarenta Ladrões',
                'Un cuento de magia, misterio y valor, donde un “ábrete sésamo” guarda un gran tesoro interior. 🪔💰',
                'A tale of courage, mystery, and gold, with "open sesame" a secret to behold. 🪔💰',
                'Um conto de coragem, segredo e emoção, com “abre-te sésamo” e um tesouro no coração. 🪔💰',
                '3ea6fc9d-aa39-4460-b2d2-5f85772bafdd_cover_.png',
                '3ea6fc9d-aa39-4460-b2d2-5f85772bafdd.png',
                NULL,
                '3ea6fc9d-aa39-4460-b2d2-5f85772bafdd.MP3',
                1, 
                1,
                0,
                '#c37d46',
                NULL,
                '#c37d46',
                '#80210e',
                '#64d2da',
                '#2c4553',
                '#1d757b',
                '#7c5a43',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '484ecc96-e2ae-44b2-aeff-c9112dc18bf5',
                'La Sirenita',
                'The Little Mermaid',
                'A Pequena Sereia',
                'Una sirenita valiente y soñadora, que sigue su voz en una aventura encantadora.',
                'A brave and dreamy little mermaid, who follows her voice on a charming adventure.',
                'Uma sereiazinha corajosa e sonhadora, que segue sua voz em uma aventura encantadora.',
                '484ecc96-e2ae-44b2-aeff-c9112dc18bf5_cover_.jpeg',
                '484ecc96-e2ae-44b2-aeff-c9112dc18bf5.jpeg',
                NULL,
                '484ecc96-e2ae-44b2-aeff-c9112dc18bf5.MP3',
                1, 
                1,
                0,
                '#d27b2f',
                NULL,
                '#d27b2f',
                '#04608c',
                '#f2eca2',
                '#3d5b55',
                '#c3cea3',
                '#5e92a1',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '50095690-b132-44c8-b8af-7f0485a89c27',
                'Jack y los Frijoles Mágicos',
                'Jack and the Magic Beans',
                'João e os Feijões Mágicos',
                'Cuento clásico de un niño valiente y curioso, que trepó hacia los cielos en un viaje asombroso. 🌱🌟',
                'A classic tale of a brave, curious boy, who climbed to the sky and found more than a toy. 🌱🌟',
                'Um conto clássico de coragem e emoção, subindo pelos céus com o coração. 🌱🌟',
                '50095690-b132-44c8-b8af-7f0485a89c27_cover_.png',
                '50095690-b132-44c8-b8af-7f0485a89c27.png',
                NULL,
                '50095690-b132-44c8-b8af-7f0485a89c27.mp3',
                1, 
                1,
                0,
                '#c87934',
                NULL,
                '#c87934',
                '#8c380d',
                '#f4d9a1',
                '#2d4c2f',
                '#c9c8ad',
                '#959567',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '55a6c0b8-9c46-4f61-b3a3-5500f3485f4d',
                ' 🦁 El León y el Ratón, Gran Corazón 🐭',
                '🦁 The Lion and the Mouse, Big Heart 🐭',
                '🦁 O Leão e o Ratinho, Grande Coração 🐭',
                'Un ratón valiente y un león agradecido descubren que la amistad 🦁 puede cambiarlo todo.',
                ' A brave mouse and a grateful lion learn that friendship 🦁 can change everything.',
                'Um ratinho corajoso e um leão agradecido descobrem que a amizade 🦁 pode mudar tudo.',
                '55a6c0b8-9c46-4f61-b3a3-5500f3485f4d_cover_.png',
                '55a6c0b8-9c46-4f61-b3a3-5500f3485f4d.png',
                NULL,
                '55a6c0b8-9c46-4f61-b3a3-5500f3485f4d.MP3',
                1, 
                1,
                0,
                '#e88c0e',
                NULL,
                '#e88c0e',
                '#743604',
                '#3db5e3',
                '#576034',
                '#c6cbac',
                '#64ad91',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '5b2414a5-603f-458d-8381-67ac40df34d8',
                'El Gato con Botas',
                'Puss in Boots',
                'O Gato de Botas',
                '"Cuento inspirado en El Gato con Botas, una historia sobre ingenio y cómo la astucia puede ayudarte a lograr cosas sorprendentes."',
                '"Story inspired by Puss in Boots, a tale about cleverness and how wit can help you achieve amazing things."',
                '"História inspirada em O Gato de Botas, uma história sobre esperteza e como a astúcia pode ajudá-lo a realizar coisas surpreendentes."',
                '5b2414a5-603f-458d-8381-67ac40df34d8_cover_.jpeg',
                '5b2414a5-603f-458d-8381-67ac40df34d8.jpeg',
                NULL,
                '5b2414a5-603f-458d-8381-67ac40df34d8.mp3',
                1, 
                1,
                0,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '5eeb3786-cfd0-4308-b50d-584806e66dfe',
                '🎨❤️ Frida y los Colores del Coraje',
                ' 🎨❤️ Frida and the Colors of Courage',
                '🎨❤️ Frida e as Cores da Coragem',
                'Cuento inspirado en Frida, una historia sobre creatividad y valentía, donde aprenderás cómo transformar los desafíos en arte.',
                'A story inspired by Frida, about creativity and courage, where you''ll learn how to turn challenges into art.',
                'Conto inspirado em Frida, uma história sobre criatividade e coragem, onde você aprenderá a transformar desafios em arte.',
                '5eeb3786-cfd0-4308-b50d-584806e66dfe_cover_.jpeg',
                '5eeb3786-cfd0-4308-b50d-584806e66dfe.jpeg',
                NULL,
                '5eeb3786-cfd0-4308-b50d-584806e66dfe.mp3',
                2, 
                1,
                0,
                '#da741e',
                NULL,
                '#da741e',
                '#7a0720',
                '#f8ec9d',
                '#203b25',
                '#d6ccc5',
                '#a55c54',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '695c4c9e-49c8-4c48-bc03-e0e27ea11e16',
                'La princesa y el secreto bajo el colchón',
                'The Princess and the Secret Under the Mattress',
                'A princesa e o segredo debaixo do colchão',
                'Una historia delicada y divertida, donde un guisante revela quién tiene alma real.',
                'A tiny pea tells a tale of truth—who has a royal soul, and proof!',
                'Um conto sensível e encantado, onde uma ervilha revela um coração coroado.',
                '695c4c9e-49c8-4c48-bc03-e0e27ea11e16_cover_.png',
                '695c4c9e-49c8-4c48-bc03-e0e27ea11e16.png',
                NULL,
                '695c4c9e-49c8-4c48-bc03-e0e27ea11e16.MP3',
                1, 
                1,
                0,
                '#e58a0c',
                NULL,
                '#e58a0c',
                '#9b4f06',
                '#f6b767',
                '#6a573f',
                '#b4c1b5',
                '#967862',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '699a22cb-464e-4b29-a9c7-48377a41b98f',
                'Paz Interior para Dormir – 432 Hz',
                ' Inner Peace for Sleep – 432 Hz',
                'Paz Interior para Dormir – 432 Hz',
                'Una melodía suave que ayuda a calmar la mente, relajar el cuerpo y dormir con tranquilidad. Ideal para acompañar los cuentos antes de dormir. 🌙✨',
                'A gentle melody that helps calm the mind, relax the body, and drift into peaceful sleep. Perfect for bedtime stories. 🌙✨',
                'Uma melodia suave que acalma a mente, relaxa o corpo e embala o sono com tranquilidade. Ideal para acompanhar contos antes de dormir. 🌙✨',
                '699a22cb-464e-4b29-a9c7-48377a41b98f_cover_.png',
                '699a22cb-464e-4b29-a9c7-48377a41b98f.png',
                NULL,
                '699a22cb-464e-4b29-a9c7-48377a41b98f.mp3',
                3, 
                1,
                0,
                '#e19b33',
                NULL,
                '#e19b33',
                '#6c3915',
                '#efb95b',
                '#284553',
                '#8b5d0d',
                '#a08c5e',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '6addde71-fdd6-4ce5-8470-178cee6cd6a9',
                '🛠️🧠 Leonardo y los Sueños que Volaban',
                '🛠️🧠 Leonardo and the Dreams that Flew',
                '🛠️🧠 Leonardo e os Sonhos que Voavam',
                'Leonardo hacía dibujos sin fin, soñando con alas… ¡y volando en su jardín!',
                ' Leonardo drew stars with a grin, and flew with his dreams from deep within.',
                'Leonardo desenhava sem fim… sonhava com asas e voava no jardim!',
                '6addde71-fdd6-4ce5-8470-178cee6cd6a9_cover_.png',
                '6addde71-fdd6-4ce5-8470-178cee6cd6a9.png',
                NULL,
                '6addde71-fdd6-4ce5-8470-178cee6cd6a9.mp3',
                2, 
                1,
                0,
                '#e6862f',
                NULL,
                '#e6862f',
                '#5d2419',
                '#f3c287',
                '#5b3548',
                '#d5b3a7',
                '#a36457',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '6af93dac-353e-4356-a452-ed2d1992e2cf',
                '🎾☀️ Serena y la Fuerza de su Raqueta',
                '🎾☀️ Serena and the Strength of Her Racket',
                '🎾☀️ Serena e a Força da Sua Raquete',
                ' Cuento inspirado en Serena, una niña soñadora que con esfuerzo, valentía y determinación aprendió a ganar en la cancha... y en la vida.',
                'A story inspired by Serena, a dreamy girl who, through effort, courage, and determination, learned to win on the court… and in life.',
                'Conto inspirado em Serena, uma menina sonhadora que, com esforço, coragem e determinação, aprendeu a vencer nas quadras... e na vida.',
                '6af93dac-353e-4356-a452-ed2d1992e2cf_cover_.jpg',
                '6af93dac-353e-4356-a452-ed2d1992e2cf.jpg',
                NULL,
                '6af93dac-353e-4356-a452-ed2d1992e2cf.mp3',
                2, 
                1,
                0,
                '#bc6538',
                NULL,
                '#bc6538',
                '#8a3529',
                '#fcb2a7',
                '#61322e',
                '#d1a89e',
                '#917869',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '6e0d9f87-bce6-4d7e-b6e7-d95d85c96db1',
                'Canción de Cuna',
                'Lullaby',
                'Canção de Ninar',
                '"Una suave melodía llena de calidez para arrullar y ayudar a los más pequeños a dormir plácidamente."',
                '"A gentle melody full of warmth to lull and help little ones sleep peacefully."',
                '"Uma suave melodia cheia de calor para embalar e ajudar os pequenos a dormir tranquilamente."',
                '6e0d9f87-bce6-4d7e-b6e7-d95d85c96db1_cover_.jpg',
                '6e0d9f87-bce6-4d7e-b6e7-d95d85c96db1.jpg',
                NULL,
                '6e0d9f87-bce6-4d7e-b6e7-d95d85c96db1.mp3',
                3, 
                1,
                0,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '6faab0a2-bc5c-4e25-be51-882cc1a84618',
                'Pinocho',
                'Pinocchio',
                'Pinóquio',
                '"Cuento inspirado en Pinocho, una historia sobre honestidad y cómo decir la verdad te acerca a ser una mejor persona."',
                '"Story inspired by Pinocchio, a tale about honesty and how telling the truth brings you closer to being a better person."',
                '"História inspirada em Pinóquio, uma história sobre honestidade e como dizer a verdade o aproxima de ser uma pessoa melhor."',
                '6faab0a2-bc5c-4e25-be51-882cc1a84618_cover_.jpeg',
                '6faab0a2-bc5c-4e25-be51-882cc1a84618.jpeg',
                NULL,
                '6faab0a2-bc5c-4e25-be51-882cc1a84618.mp3',
                1, 
                1,
                1,
                '#cb7840',
                NULL,
                '#cb7840',
                '#871614',
                '#e2b48b',
                '#7d6d4a',
                '#a1bacb',
                '#b7887d',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '79afb2f4-a2cc-4537-a233-850c5aed618d',
                'Aladino y la Lámpara Mágica',
                'Aladdin and the Magic Lamp',
                'Aladim e a Lâmpada Mágica',
                'Un niño curioso encontró, por azar del destino, una lámpara brillante… ¡y un genio travieso y divino! 🪔✨',
                'A curious boy found a lamp full of light, and a playful genie who changed his night. 🪔✨',
                'Um menino curioso achou com emoção, uma lâmpada mágica com um gênio do coração. 🪔✨',
                '79afb2f4-a2cc-4537-a233-850c5aed618d_cover_.png',
                '79afb2f4-a2cc-4537-a233-850c5aed618d.png',
                NULL,
                '79afb2f4-a2cc-4537-a233-850c5aed618d.MP3',
                1, 
                1,
                0,
                '#b86c3b',
                NULL,
                '#b86c3b',
                '#752407',
                '#edb76e',
                '#323749',
                '#c6a07c',
                '#9c8464',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '8e17fde6-86d8-4c5c-a61c-552ed8051f04',
                'Rapunzel',
                'Rapunzel',
                'Rapunzel',
                '"Cuento inspirado en Rapunzel, una historia sobre valentía y cómo la esperanza puede llevarte a encontrar la libertad."',
                '"Story inspired by Rapunzel, a tale about bravery and how hope can lead you to find freedom."',
                '"História inspirada em Rapunzel, uma história sobre coragem e como a esperança pode levá-la a encontrar a liberdade."',
                '8e17fde6-86d8-4c5c-a61c-552ed8051f04_cover_.jpeg',
                '8e17fde6-86d8-4c5c-a61c-552ed8051f04.jpeg',
                NULL,
                '8e17fde6-86d8-4c5c-a61c-552ed8051f04.mp3',
                1, 
                1,
                0,
                '#eeac39',
                NULL,
                '#eeac39',
                '#804212',
                '#f8ea7f',
                '#283c48',
                '#e2d2bd',
                '#5e53a5',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '92f614c8-81dd-4d60-9add-a204b160812e',
                'Blanca Nieves',
                'Snow White',
                'Branca de Neve',
                '"Cuento inspirado en Blanca Nieves, una historia mágica sobre la bondad y cómo el coraje puede superar cualquier obstáculo."',
                '"Story inspired by Snow White, a magical tale about kindness and how courage can overcome any obstacle."',
                '"História inspirada em Branca de Neve, uma história mágica sobre bondade e como a coragem pode superar qualquer obstáculo."',
                '92f614c8-81dd-4d60-9add-a204b160812e_cover_.jpeg',
                '92f614c8-81dd-4d60-9add-a204b160812e.jpeg',
                NULL,
                '92f614c8-81dd-4d60-9add-a204b160812e.mp3',
                1, 
                1,
                0,
                '#e4840f',
                NULL,
                '#e4840f',
                '#041b84',
                '#f7d874',
                '#2c644e',
                '#848abd',
                '#af9061',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                '96df8eef-b9cb-416a-9443-b9e49557523e',
                '"Ada Lovelace Dedicado a Valentina"',
                '"Ada Lovelace Dedicated to Valentina"',
                '"Ada Lovelace Dedicado a Valentina"',
                '"Cuento inspirado en Ada Lovelace dedicado a Valentina."',
                '"Story inspired by Ada Lovelace dedicated to Valentina."',
                '"História inspirada em Ada Lovelace dedicada a Valentina."',
                '96df8eef-b9cb-416a-9443-b9e49557523e_cover_.jpeg',
                '96df8eef-b9cb-416a-9443-b9e49557523e.jpeg',
                NULL,
                '96df8eef-b9cb-416a-9443-b9e49557523e.mp3',
                4, 
                1,
                0,
                '#3dcfa5',
                NULL,
                '#3dcfa5',
                '#541c14',
                '#e4a49c',
                '#6b313e',
                '#a4accc',
                '#a46452',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'a23432da-f9e9-45f6-8d29-6dfb261d349f',
                'Música Relajante Arpa y Piano Instrumental',
                'Relaxing Music Harp and Piano Instrumental',
                'Música Relaxante Harpa e Piano Instrumental',
                '"Melodías suaves de arpa y piano para calmar la mente y disfrutar de un descanso profundo."',
                '"Gentle harp and piano melodies to soothe the mind and enjoy a deep rest."',
                '"Melodias suaves de harpa e piano para acalmar a mente e desfrutar de um descanso profundo."',
                'a23432da-f9e9-45f6-8d29-6dfb261d349f_cover_.jpeg',
                'a23432da-f9e9-45f6-8d29-6dfb261d349f.jpeg',
                NULL,
                'a23432da-f9e9-45f6-8d29-6dfb261d349f.mp3',
                3, 
                1,
                0,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'a60cff0a-0879-4a91-8873-910a4d5956cc',
                ' 🏀☀️ Mike y el Gran Salto de los Sueños',
                '🏀☀️ Mike and the Great Leap of Dreams',
                '🏀☀️ Mike e o Grande Salto dos Sonhos',
                'Mike saltaba con ilusión… y con cada caída, más brillaba su corazón.',
                'Mike jumped with joy and no fear… and each fall made his heart shine clear.',
                'Mike pulava com emoção… e a cada queda, brilhava o coração!',
                'a60cff0a-0879-4a91-8873-910a4d5956cc_cover_.jpeg',
                'a60cff0a-0879-4a91-8873-910a4d5956cc.jpeg',
                NULL,
                'a60cff0a-0879-4a91-8873-910a4d5956cc.MP3',
                2, 
                1,
                0,
                '#b31107',
                NULL,
                '#b31107',
                '#7a2a15',
                '#fbe9a9',
                '#393745',
                '#d4cead',
                '#915b52',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'a7501394-bf0e-433b-8647-0508cffabe6f',
                'La Tortuga y la Liebre',
                'The Tortoise and the Hare',
                'A Tartaruga e a Lebre',
                '"Cuento inspirado en La Tortuga y la Liebre, una historia sobre constancia y cómo la paciencia puede vencer la prisa."',
                '"Story inspired by The Tortoise and the Hare, a tale about perseverance and how patience can outpace haste."',
                '"História inspirada em A Tartaruga e a Lebre, uma história sobre perseverança e como a paciência pode superar a pressa."',
                'a7501394-bf0e-433b-8647-0508cffabe6f_cover_.jpeg',
                'a7501394-bf0e-433b-8647-0508cffabe6f.jpeg',
                NULL,
                'a7501394-bf0e-433b-8647-0508cffabe6f.mp3',
                1, 
                1,
                0,
                '#0e81cc',
                NULL,
                '#0e81cc',
                '#055fb6',
                '#7ea2fa',
                '#306239',
                '#bfab7e',
                '#5873ab',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'a7f4748b-e5b5-442b-9de5-1c5196782d8a',
                'Caperucita Roja',
                'Little Red Riding Hood',
                'Chapeuzinho Vermelho',
                '"Cuento inspirado en Caperucita Roja, una historia sobre el valor y cómo ser valiente puede ayudarte a enfrentar cualquier peligro."',
                '"Story inspired by Little Red Riding Hood, a tale about bravery and how being courageous can help you face any danger."',
                '"História inspirada em Chapeuzinho Vermelho, uma história sobre coragem e como ser valente pode ajudá-lo a enfrentar qualquer perigo."',
                'a7f4748b-e5b5-442b-9de5-1c5196782d8a_cover_.jpeg',
                'a7f4748b-e5b5-442b-9de5-1c5196782d8a.jpeg',
                NULL,
                'a7f4748b-e5b5-442b-9de5-1c5196782d8a.mp3',
                1, 
                1,
                0,
                '#e82033',
                NULL,
                '#e82033',
                '#8e0a1f',
                '#f6a966',
                '#2f5c59',
                '#9fca91',
                '#789870',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'a9c83f84-ee3c-49b7-95bd-705c4d854006',
                'Los Tres Cerditos',
                'The Three Little Pigs',
                'Os Três Porquinhos',
                '"Cuento inspirado en Los Tres Cerditos, una historia sobre esfuerzo y cómo construir con cuidado te prepara para cualquier desafío."',
                '"Story inspired by The Three Little Pigs, a tale about hard work and how building carefully prepares you for any challenge."',
                '"História inspirada em Os Três Porquinhos, uma história sobre esforço e como construir com cuidado prepara você para qualquer desafio."',
                'a9c83f84-ee3c-49b7-95bd-705c4d854006_cover_.jpeg',
                'a9c83f84-ee3c-49b7-95bd-705c4d854006.jpeg',
                NULL,
                'a9c83f84-ee3c-49b7-95bd-705c4d854006.mp3',
                1, 
                1,
                0,
                '#d98d3a',
                NULL,
                '#d98d3a',
                '#884419',
                '#e59b83',
                '#335142',
                '#b87761',
                '#8a964f',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'ae4537de-27f0-45fd-863b-f38f8c34e46a',
                'Ricitos de Oro',
                'Goldilocks',
                'Cachinhos Dourados',
                '"Cuento inspirado en Ricitos de Oro, una historia sobre curiosidad y cómo encontrar el equilibrio perfecto puede llevarte a nuevas aventuras."',
                '"Story inspired by Goldilocks, a tale about curiosity and how finding the perfect balance can lead to new adventures."',
                '"História inspirada em Cachinhos Dourados, uma história sobre curiosidade e como encontrar o equilíbrio perfeito pode levar a novas aventuras."',
                'ae4537de-27f0-45fd-863b-f38f8c34e46a_cover_.jpeg',
                'ae4537de-27f0-45fd-863b-f38f8c34e46a.jpeg',
                NULL,
                'ae4537de-27f0-45fd-863b-f38f8c34e46a.mp3',
                1, 
                1,
                0,
                '#dc9225',
                NULL,
                '#dc9225',
                '#75310f',
                '#f0bb6f',
                '#38705d',
                '#d6b8a1',
                '#5fa07b',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'af449935-757e-49bf-9371-f9c368c6fe4c',
                '5.0 leonardo para matías',
                '5.0 leonardo para matías',
                '5.0 leonardo para matías',
                'Cuento dedicado a matías',
                'Cuento dedicado a matías',
                'Cuento dedicado a matías',
                'af449935-757e-49bf-9371-f9c368c6fe4c_cover_.png',
                'af449935-757e-49bf-9371-f9c368c6fe4c.png',
                NULL,
                'af449935-757e-49bf-9371-f9c368c6fe4c.undefined',
                4, 
                1,
                0,
                '#e6862f',
                NULL,
                '#e6862f',
                '#5d2419',
                '#f3c287',
                '#5b3548',
                '#d5b3a7',
                '#a36457',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'b2f60f23-c355-4e39-b718-8142fba192f8',
                '“Nico y los Rayos de la Imaginación”',
                '“Nico and the Lightning of Imagination”',
                '“Nico e os Raios da Imaginação”',
                'Un cuento brillante ⚡ donde la chispa de un niño crea ideas que iluminan el corazón.',
                'A dazzling tale ⚡ where one boy’s spark lights up hearts and dreams with invention.',
                'Uma história brilhante ⚡ onde um menino acende sonhos com sua imaginação brilhante.',
                'b2f60f23-c355-4e39-b718-8142fba192f8_cover_.png',
                'b2f60f23-c355-4e39-b718-8142fba192f8.png',
                NULL,
                'b2f60f23-c355-4e39-b718-8142fba192f8.MP3',
                2, 
                1,
                0,
                '#f19122',
                NULL,
                '#f19122',
                '#7a4506',
                '#f2c864',
                '#2e5d63',
                '#94a47c',
                '#9d8d59',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'b9b3798f-88cd-4989-926e-985dc1437ead',
                'El Sastrecillo Valiente',
                'The Brave Little Tailor',
                'O Pequeno Alfaiate Valente',
                '✨ "Cuento inspirado en El Sastrecillo Valiente, una historia sobre astucia, valentía y cómo la inteligencia puede superar cualquier obstáculo."',
                '✨ "Story inspired by The Brave Little Tailor, a tale of cleverness, courage, and how intelligence can overcome any challenge."',
                '✨ "Conto inspirado em O Alfaiate Valente, uma história sobre astúcia, coragem e como a inteligência pode superar qualquer desafio."',
                'b9b3798f-88cd-4989-926e-985dc1437ead_cover_.jpg',
                'b9b3798f-88cd-4989-926e-985dc1437ead.jpg',
                NULL,
                'b9b3798f-88cd-4989-926e-985dc1437ead.mp3',
                1, 
                1,
                0,
                '#d48318',
                NULL,
                '#d48318',
                '#62126f',
                '#f2c590',
                '#5d314b',
                '#73bdb8',
                '#6f5595',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'c0739c00-4171-434c-b23e-aefd014d343d',
                '💻💡 Ada y el Lenguaje Invisible',
                '💻💡 Ada and the Invisible Language',
                '💻💡 Ada e a Linguagem Invisível',
                'Ada pensaba en ritmo y canción… ¡y hacía que los números bailaran de emoción!',
                'Ada dreamed in numbers and grace… turning math into a magical place!',
                'Ada sonhava com cálculo e cor… e fazia da lógica puro amor!',
                'c0739c00-4171-434c-b23e-aefd014d343d_cover_.jpg',
                'c0739c00-4171-434c-b23e-aefd014d343d.png',
                NULL,
                'c0739c00-4171-434c-b23e-aefd014d343d.mp3',
                2, 
                1,
                0,
                '#ea7e1f',
                NULL,
                '#ea7e1f',
                '#612422',
                '#eec19f',
                '#713f3e',
                '#a1cbc4',
                '#b1604f',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'c157a839-3784-42fa-af52-9c51dcc00879',
                '🌊⭐ Diana y el Mar que Soñaba Cruzar',
                '🌊⭐ Diana and the Sea She Dreamed to Cross',
                '🌊⭐ Diana e o Mar que Sonhava Cruzar',
                ' Diana nadaba con gran corazón… ¡y cruzó los mares con pura ilusión!',
                ' Diana swam with all her might… her dream lit oceans day and night!',
                ' Diana nadava com o coração… e fazia do mar sua inspiração!',
                'c157a839-3784-42fa-af52-9c51dcc00879_cover_.jpg',
                'c157a839-3784-42fa-af52-9c51dcc00879.jpg',
                NULL,
                'c157a839-3784-42fa-af52-9c51dcc00879.mp3',
                2, 
                1,
                0,
                '#11afc7',
                NULL,
                '#11afc7',
                '#093879',
                '#8ce4f3',
                '#253353',
                '#a6d4bc',
                '#637f8c',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'c48af433-be1c-4dfc-a277-b21d93ad5de3',
                '🎾🔥 Rafa y el Corazón de la Cancha',
                '🎾🔥 Rafa and the Heart of the Court',
                '🎾🔥 Rafa e o Coração da Quadra',
                'Cuento inspirado en Rafa, que aprendió con emoción, que la fuerza verdadera nace siempre del corazón.',
                'Story of Rafa, who found the key: true strength lives where the heart beats free.',
                'Rafa aprendeu com paixão, que a força maior vem do coração.',
                'c48af433-be1c-4dfc-a277-b21d93ad5de3_cover_.png',
                'c48af433-be1c-4dfc-a277-b21d93ad5de3.png',
                NULL,
                'c48af433-be1c-4dfc-a277-b21d93ad5de3.MP3',
                2, 
                1,
                0,
                '#df7819',
                NULL,
                '#df7819',
                '#701c05',
                '#f9c678',
                '#5c4030',
                '#925b06',
                '#8d6954',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'c61a80d6-78c3-41ab-9ef7-c18522924336',
                'El Vals de las Flores Mágicas – 432 Hz',
                'The Waltz of the Magical Flowers – 432 Hz',
                'A Valsa das Flores Mágicas – 432 Hz',
                'Una danza de pétalos que giran sin cesar, como un cuento de hadas que empieza a sonar. 🌸🎻',
                ' A dance of petals floating through the air, like a fairy tale blooming with music and flair. 🌸🎻',
                'Uma dança de pétalas no ar a girar, como um conto encantado a se revelar. 🌸🎻',
                'c61a80d6-78c3-41ab-9ef7-c18522924336_cover_.png',
                'c61a80d6-78c3-41ab-9ef7-c18522924336.png',
                NULL,
                'c61a80d6-78c3-41ab-9ef7-c18522924336.mp3',
                3, 
                1,
                0,
                '#e8733d',
                NULL,
                '#e8733d',
                '#6e1707',
                '#e3b173',
                '#44363a',
                '#bb8874',
                '#90846d',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'cc6ba3f9-6088-41fa-97a8-9f67b14de537',
                '🌙📖 Hipatia y los Secretos del Universo',
                '🌙📖 Hypatia and the Secrets of the Universe',
                '🌙📖 Hipátia e os Segredos do Universo',
                'Cuento de Hipatia, niña pensadora, que buscó entre estrellas la luz que transforma.',
                ' Hypatia dreamed with the sky so wide, seeking truths the stars would hide.',
                'Hipátia viajava no céu sem fim, buscando saber além de mim.',
                'cc6ba3f9-6088-41fa-97a8-9f67b14de537_cover_.png',
                'cc6ba3f9-6088-41fa-97a8-9f67b14de537.png',
                NULL,
                'cc6ba3f9-6088-41fa-97a8-9f67b14de537.MP3',
                2, 
                1,
                0,
                '#da8a18',
                NULL,
                '#da8a18',
                '#08617a',
                '#f7c024',
                '#334f59',
                '#936e05',
                '#66956f',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'cf1c36d7-b490-4250-957d-0ee9725261f0',
                'Cenicienta',
                'Cinderella',
                'Cinderela',
                '"Cuento inspirado en la vida de Cenicienta, una historia sobre la esperanza y cómo la bondad puede transformar hasta los sueños más grandes en realidad."',
                '"Story inspired by the life of Cinderella, a tale about hope and how kindness can turn even the biggest dreams into reality."',
                '"História inspirada na vida de Cinderela, uma história sobre esperança e como a bondade pode transformar até os maiores sonhos em realidade."',
                'cf1c36d7-b490-4250-957d-0ee9725261f0_cover_.jpeg',
                'cf1c36d7-b490-4250-957d-0ee9725261f0.jpeg',
                NULL,
                'cf1c36d7-b490-4250-957d-0ee9725261f0.mp3',
                1, 
                1,
                0,
                '#2bb7db',
                NULL,
                '#2bb7db',
                '#073b76',
                '#ecb88e',
                '#305b64',
                '#cbc0b5',
                '#5eac8c',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'd2088457-c274-4662-bfa4-5f8869033a0f',
                '🪄📖 Jhoanna y la Pluma de los Mundos Invisibles',
                '🪄📖 Jhoanna and the Quill of Invisible Worlds',
                ' 🪄📖 Jhoanna e a Pena dos Mundos Invisíveis',
                'Jhoane escribía con el corazón… y hacía del miedo, pura imaginación.',
                ' Jhoane wrote with a glowing heart… turning fear into magic from the start.',
                ' Jhoane escrevia com emoção… e transformava o medo em inspiração!',
                'd2088457-c274-4662-bfa4-5f8869033a0f_cover_.png',
                'd2088457-c274-4662-bfa4-5f8869033a0f.png',
                NULL,
                'd2088457-c274-4662-bfa4-5f8869033a0f.mp3',
                2, 
                1,
                0,
                '#dc6c0c',
                NULL,
                '#dc6c0c',
                '#873906',
                '#edbc52',
                '#5c3c34',
                '#8a630e',
                '#914707',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'd20ad049-5833-4915-92d5-aa9d672ff371',
                '🎸🌞 Carlitos y la Canción del Corazón Alegre',
                '🎸🌞 Carlitos and the Song of the Joyful Heart',
                '🎸🌞 Carlitos e a Canção do Coração Alegre',
                'Carlitos cantaba con voz y pasión, llenando el mundo de luz y emoción.',
                'Carlitos sang with heart and soul, turning music into joy and goal.',
                'Carlitos cantava com emoção e luz, espalhando alegria por onde conduz.',
                'd20ad049-5833-4915-92d5-aa9d672ff371_cover_.png',
                'd20ad049-5833-4915-92d5-aa9d672ff371.png',
                NULL,
                'd20ad049-5833-4915-92d5-aa9d672ff371.mp3',
                2, 
                1,
                0,
                '#d58117',
                NULL,
                '#d58117',
                '#773811',
                '#fcad55',
                '#5d4235',
                '#abc8cd',
                '#967555',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'd22ca2a7-7554-4a2e-a1a6-459e7593f2ab',
                '🎤La niña que habló con valentía',
                '🎤The girl who changed the world with her voice',
                '🎤A menina que mudou o mundo com sua voz',
                'Con voz decidida y alma brillante, hizo del mundo un lugar inspirador.',
                'With a fearless voice and a shining soul, she made the world an inspiring place.',
                'Com voz corajosa e alma brilhante, tornou o mundo um lugar inspirador.',
                'd22ca2a7-7554-4a2e-a1a6-459e7593f2ab_cover_.png',
                'd22ca2a7-7554-4a2e-a1a6-459e7593f2ab.png',
                NULL,
                'd22ca2a7-7554-4a2e-a1a6-459e7593f2ab.MP3',
                2, 
                1,
                0,
                '#e67905',
                NULL,
                '#e67905',
                '#c63707',
                '#4cb4f4',
                '#3b6c7a',
                '#d9bab0',
                '#56986d',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'ddd504f3-35b3-416f-9542-e0da2a826e62',
                'Hansel y Gretel',
                'Hansel and Gretel',
                'João e Maria',
                '"Cuento inspirado en Hansel y Gretel, una historia sobre valentía y cómo la unión puede superar cualquier desafío."',
                '"Story inspired by Hansel and Gretel, a tale about bravery and how unity can overcome any challenge."',
                '"História inspirada em João e Maria, uma história sobre coragem e como a união pode superar qualquer desafio."',
                'ddd504f3-35b3-416f-9542-e0da2a826e62_cover_.jpeg',
                'ddd504f3-35b3-416f-9542-e0da2a826e62.jpeg',
                NULL,
                'ddd504f3-35b3-416f-9542-e0da2a826e62.mp3',
                1, 
                1,
                0,
                '#dc701e',
                NULL,
                '#dc701e',
                '#824811',
                '#eed1a6',
                '#4e3c34',
                '#a9c9b1',
                '#989f56',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'eae114f4-9507-430f-85b6-ba4799820e51',
                '💡🔧 Tomás y la Luz que Nació de la Paciencia',
                '💡🔧 Thomas and the Light Born from Patience',
                '💡🔧 Tomás e a Luz Nascida da Paciência',
                ' Tomás probó mil veces sin parar… ¡hasta que una idea lo hizo brillar!',
                'Tomás tried and tried with all his might… ‘til one small spark gave him light!',
                'Tomás tentou sem nunca cansar… e uma ideia fez tudo brilhar!',
                'eae114f4-9507-430f-85b6-ba4799820e51_cover_.jpeg',
                'eae114f4-9507-430f-85b6-ba4799820e51.jpeg',
                NULL,
                'eae114f4-9507-430f-85b6-ba4799820e51.mp3',
                2, 
                1,
                0,
                '#be6d19',
                NULL,
                '#be6d19',
                '#844429',
                '#eac58e',
                '#52382c',
                '#bfc4c6',
                '#9d6f53',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'ee09dbf5-a797-43c9-9f1f-b5f2ecaaac2d',
                'Cuencos Tibetanos para Dormir',
                'Tibetan Bowls for Sleep',
                'Tigelas Tibetanas para Dormir',
                '"Sonidos de cuencos tibetanos para una relajación profunda y ayudar a un sueño tranquilo y reparador."',
                '"Soothing Tibetan bowl sounds for deep relaxation and to help you sleep peacefully."',
                '"Sons relaxantes de tigelas tibetanas para uma profunda relaxação e um sono tranquilo e reparador."',
                'ee09dbf5-a797-43c9-9f1f-b5f2ecaaac2d_cover_.jpeg',
                'ee09dbf5-a797-43c9-9f1f-b5f2ecaaac2d.jpeg',
                NULL,
                'ee09dbf5-a797-43c9-9f1f-b5f2ecaaac2d.undefined',
                3, 
                1,
                0,
                '#f27e17',
                NULL,
                '#f27e17',
                '#0e477f',
                '#f0bb7e',
                '#52293d',
                '#cdac96',
                '#587e9f',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'ee94fccc-aaf8-46df-9084-244cff8022d9',
                '🎵Canción de Cuna Mágica – 432 Hz',
                'Magic Lullaby in 432 Hz',
                'Canção de Ninar Mágica – 432 Hz',
                'Una melodía suave y encantadora que ayuda a los más pequeños a soñar profundo y dormir felices. Ideal para cuentos y noches de magia. 🌌🧸',
                'A soft and magical melody that helps little ones drift into sweet dreams. Perfect for stories and peaceful nights. 🌌🧸',
                'Uma melodia suave e encantadora que embala os pequenos em sonhos doces. Perfeita para histórias e noites de magia. 🌌🧸',
                'ee94fccc-aaf8-46df-9084-244cff8022d9_cover_.png',
                'ee94fccc-aaf8-46df-9084-244cff8022d9.png',
                NULL,
                'ee94fccc-aaf8-46df-9084-244cff8022d9.mp3',
                3, 
                1,
                0,
                '#eb8315',
                NULL,
                '#eb8315',
                '#772e06',
                '#f4be84',
                '#513c36',
                '#8c4e0c',
                '#6c4c34',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'fb2b68d9-bf45-4da1-b278-a3170de7512c',
                '🧪🌟 Marie y la Luz que Descubrió en lo Invisible',
                '🧪🌟 Marie and the Light She Found in the Invisible',
                '🧪🌟 Marie e a Luz que Encontrou no Invisível',
                'Marie mezclaba sueños y color… ¡y en cada experimento brillaba su amor!',
                'Marie mixed dreams with glowing delight… her love for science made stars ignite!',
                'Marie misturava com brilho e calor… e a ciência dançava com seu amor!',
                'fb2b68d9-bf45-4da1-b278-a3170de7512c_cover_.jpeg',
                'fb2b68d9-bf45-4da1-b278-a3170de7512c.jpeg',
                NULL,
                'fb2b68d9-bf45-4da1-b278-a3170de7512c.mp3',
                2, 
                1,
                0,
                '#e68d20',
                NULL,
                '#e68d20',
                '#811f0d',
                '#f9de96',
                '#5e4634',
                '#b88375',
                '#5c83af',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
INSERT INTO History (
                id, 
                name_es, name_en, name_pt, 
                description_es, description_en, description_pt, 
                cover, poster, youtube, song,
                type, active, isPremium, 
                dominant, average, vibrant, darkVibrant, lightVibrant, darkMuted, lightMuted, muted,
                createdAt, updatedAt
            ) VALUES (
                'a665bdb4-fb56-47f2-ba70-8f90cfe4bb1e',
                '🌿 Yu y la Medicina que Ilumina Vidas ✨',
                '🌿 Yu and the Medicine that Lights Lives ✨',
                NULL,
                'Con ciencia y tradición, Yu descubrió 🌿 la fuerza de curar y transformar el mundo.',
                ' With science and tradition, Yu found 🌿 the power to heal and change the world.',
                NULL,
                'a665bdb4-fb56-47f2-ba70-8f90cfe4bb1e_cover_.png',
                'a665bdb4-fb56-47f2-ba70-8f90cfe4bb1e.png',
                NULL,
                'a665bdb4-fb56-47f2-ba70-8f90cfe4bb1e.MP3',
                2, 
                1,
                0,
                '#dc7b07',
                NULL,
                '#dc7b07',
                '#61380a',
                '#f6cc8d',
                '#626b38',
                '#adcbcd',
                '#ae8d63',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
COMMIT;